tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'homebrew/services'
tap 'homebrew/versions'

brew 'bash-completion'
brew 'git'
brew 'git-extras'
brew 'libsass'
brew 'libxml2'
brew 'node'
brew 'wget'

cask 'firefox'
cask 'google-chrome'
cask 'google-drive'
cask 'java'
cask 'skype'
cask 'spotify'
cask 'zeplin'